version: '3'
services:
  server:
    build: .
    ports:
      - '5000:5000'
    #environment:
      #MONGODB_URI: mongodb://mongo:27017/mydb
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
